### ISSUE TITLE
Component Position 문제

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#51]
Basket이라는 Component 위치 조정이 아무리해도 안되는 문제가 생겼습니다.
```javascript
//Basket.js
import React, { Component } from 'react';
import "./Component.css";

class Basket extends Component {
    render() {
      const basketStyle = {
        Position : 'fixed',
        Top : 200,
        right : 20
      }
      return (
        <article style={basketStyle}>
            <text className="BasketTitle">장바구니 {this.props.orderID}</text>
        </article>
      );
    }
  }

  export default Basket;

// component.css
.BasketTitle{
  position: fixed;
  top: 100px;
  right: 20px;
}
```
다른 컴포넌트들은 tag에 style을 통해서 위치 조정이 잘 됐었는데, 같은 방법임에도 불구하고 스타일이 적용이 안되네요..
className을 통해서 해도 안되고.. 혹시 스타일이 적용이 안되는 경우가 있나요..? 뭐가 잘못됐는지 모르겠네요 ㅠㅠ
![장바구니](https://user-images.githubusercontent.com/52308823/103357453-95c41d00-4af6-11eb-9801-5e70f25c7d9b.JPG)
이렇게 아무리 위치조정을 해도 무조건 저 위치에 겹쳐서 뜹니다.. 

```javascript
//App.js
import React, {Component} from 'react'; 
import './App.css';
import Subject from './component/Subject';
import LoginRoot from './component/LoginRoot';
import Content from './component/Content.js';
import TopBar from './containers/TopBar';
import Basket from './containers/Basket';

class App extends Component {
  render() {
    return (
      <div>
        {/* JEoN-Ha 제목 */}
        <Subject></Subject>

        {/* 로그인 폼 */}
        <LoginRoot></LoginRoot>

        {/* MENU */}
        <TopBar></TopBar>
        <Content></Content>

        {/* 장바구니 담기 */}
        <Basket></Basket>
      </div>
    )
  }
}

export default App;
```
Basket.js를 containers로 통해서 import해서 그런가 라는 생각을 했지만 똑같이 containers로 import한 TopBar는 위치조정이 잘 되더라구요..

**Comment by fora22** [comment]
작업 branch가 어디죠?

**Comment by dkfma4915** [comment]
> 작업 branch가 어디죠?

Armful/Develope/React-Redux 입니다~~

**Comment by fora22** [comment]
폴더는 `jeonha_redux` 맞나요?

**Comment by dkfma4915** [comment]
> 폴더는 `jeonha_redux` 맞나요?

맞슴당

**Comment by fora22** [comment]
![image](https://user-images.githubusercontent.com/48875566/103395444-8d5cf800-4b71-11eb-8260-8811f4ca2efa.png)

전 이렇게 뜨는데...? 정확히 어떤게 문제인지 잘 이해가 안가네요. 다시 설명 부탁드립니다.

# 현재 코드(열어봤을 때)
```js
import React, { Component } from 'react';
import styles from "./Component.css";

class Basket extends Component {
    render() {
      const basketStyle = {
        Position : 'fixed',
        Top : 200,
        right : 20
      }
      return (
        <header style={basketStyle}>
            <text className={styles.BasketTitle}>장바구니 {this.props.orderID}</text>
        </header>
      );
    }
  }

  export default Basket;
```
```css
.MainTitle {
    text-align: center;
    color:"red";
    border: 4px dashed #bcbcbc;
    text-decoration: 'none' !important; 
    /*underline 제거, 폰트 색상 제거가 안됨..*/
  }

.SubTitle{
    font-size: 20px;
}

.Login{
  flex-direction: 'row';
}

.BasketTitle{
  position: fixed;
  top: 100px;
  right: 20px;
}
```


1. 말해준 코드를 보면 `article` 속성에 `basketStyle`이 있는데 적용이 안된다?
2. `article` 속성에 `basketStyle`이 있고 `text`  속성에 `className = "BasketTitle"`이 있어서 중복된다?
3. 아니면 다른 질문??
